name: Build and Test

on:
  workflow_call:
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Check server syntax
        working-directory: ./server
        run: node -c server.js