name: Dependency Scan

on:
  workflow_call:

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Audit server dependencies
        working-directory: ./server
        run: npm audit --audit-level=high || true

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Audit client dependencies
        working-directory: ./client
        run: npm audit --audit-level=high || true